apiVersion: v1
kind: Secret
metadata:
  name: argocd-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository    # This is import to define
stringData:
  type: git
  url: https://github.com/rdumitru1/argocd-tutorial-private.git
  username: argocd-private-repo     # name of the token
  password: the_generate_token    # the generated token itself