apiVersion: v1
kind: Secret
metadata:
  name: argocd-private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository    # This is import to define
stringData:
  type: git
  url: git@github.com:rdumitru1/argocd-tutorial-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    The content of the private key
    -----END OPENSSH PRIVATE KEY-----