apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-4
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "!dev"
      server: "*"
  sourceRepos:
    - "*"
