apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-7
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
  roles:
    - name: read-only
      description: "This role can be used only for reading applications."
      policies:
        - p, proj:project-7:read-only, applications, get, project-7/*, allow
