server:
  ingress:
    enabled: true
   # controller: generic
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: "nginx"
    hostname: darkscience.local
    path: /
    pathType: Prefix
    tls: true
    # https: true
