apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prune-application
spec:
  destination:
    namespace: prune-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 03-argocd-applications/directoryofmanifests
    repoURL: https://github.com/rdumitru1/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true