apiVersion: v1
kind: Secret
metadata:
  name: local
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: pre-staging
type: Opaque
stringData:
  name: local                                     # This can be anything, it represents the NAME field in the output of argocd cluster list
  server: https://kubernetes.default.svc          # This is https://kubernetes.default.svc because it refers to the local cluster.
  config: |                                       # config
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }