apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-tracking-strategies
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: # use the version number ex: 1.16.1 || use a range ex: 1.* or 1.2.* or >=1.2.0 <1.3.0 || use the latest version ex: '*'
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helm-tracking-strategies
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}